/*
 * rdose_command_code.h
 *
 *  Created on: Feb 4, 2026
 *      Author: Kirill
 */

#ifndef SRC_RDOSE_COMMAND_CODE_H_
#define SRC_RDOSE_COMMAND_CODE_H_

#include <stdint.h>

typedef enum
{
	// executions - tcp and uart
	COMMAND_EMPTY = 0x00,
	COMMAND_ENABLE_HV_A = 0x01,
	COMMAND_ENABLE_HV_B = 0x02,
	COMMAND_DISABLE_HV_A  = 0x03,
	COMMAND_DISABLE_HV_B = 0x04,
	COMMAND_SET_VOLTAGE_A = 0x05,
	COMMAND_SET_VOLTAGE_B = 0x06,
	COMMAND_SET_HV_POLARITY_A = 0x07,
	COMMAND_SET_HV_POLARITY_B = 0x08,
	COMMAND_SET_SENSITIVITY_A = 0x09,
	COMMAND_SET_SENSITIVITY_B = 0x0A,
	//COMMAND_SET_BROAD_RANGE_A = 0x09,
	//COMMAND_SET_BROAD_RANGE_B = 0x0A,
	//COMMAND_SET_NARROW_RANGE_A = 0x0B,
	//COMMAND_SET_NARROW_RANGE_B = 0x0C,

	// telemetry request - uart only
	COMMAND_GET_MESSAGE_NO = 0x80,
	COMMAND_GET_DOSE_A = 0x81,
	COMMAND_GET_DOSE_B = 0x82,
	COMMAND_GET_HV_A = 0x83,
	COMMAND_GET_HV_B = 0x84,
	COMMAND_GET_HV_POL_A = 0x85,
	COMMAND_GET_HV_POL_B = 0x86,
	COMMAND_GET_HV_EN_A = 0x87,
	COMMAND_GET_HV_EN_B = 0x88,
	COMMAND_GET_RANGE_A = 0x89,
	COMMAND_GET_RANGE_B = 0x8A,
	COMMAND_GET_TEMP = 0x8B
} command_code_t;

#endif /* SRC_RDOSE_COMMAND_CODE_H_ */
